### cadastra
POST http://localhost:3000/users
Content-Type: application/json

{
	"email": "teste@email.com",
	"senha": "senha123"
}


### buscaPorId
GET http://localhost:3000/users/2


### altera
PUT http://localhost:3000/users/2
Content-Type: application/json

{
	"email": "ruan@email.com.br"
	,"senha": "1234"
}


### deleta
DELETE http://localhost:3000/users/1


### login
POST http://localhost:3000/users/login
Content-Type: application/json

{
	"email": "ruan@email.com.br"
	,"senha": "1234"
}
